global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "dln-indexer"
    static_configs:
      - targets: ["host.docker.internal:9090"]
        labels:
          service: indexer

  - job_name: "dln-api"
    static_configs:
      - targets: ["host.docker.internal:3002"]
        labels:
          service: api
    metrics_path: /metrics
