replicaCount: 1

image:
  repository: dln-indexer
  tag: latest
  pullPolicy: IfNotPresent

env:
  CLICKHOUSE_HOST: "http://clickhouse:8123"
  CLICKHOUSE_DATABASE: "dln"
  CLICKHOUSE_USER: "dln_admin"
  CLICKHOUSE_PASSWORD: "G6lxIxGvddWE5eTJ"
  REDIS_URL: "redis://:password@redis:6379"
  SOLANA_RPC_URL: "https://api.mainnet-beta.solana.com"
  SOLANA_RPS: "10"
  INDEXER_BATCH_SIZE: "50"
  INDEXER_DELAY_MS: "10000"
  JUPITER_API_KEY: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

nameOverride: ""
fullnameOverride: ""
